// Note: We use duck-typing with extensions rather than interfaces because
// ProjectEntity and SessionEntity are generated by Drift and cannot
// directly implement interfaces.

// Both entities already have: id, isStarred, isArchived, createdAt, updatedAt
// We just need to add displayName via extensions.

/// Interface for DAOs that manage listable entities.
///
/// Provides standard CRUD operations used by [SelectableListView]
/// to implement default behaviors without explicit callbacks.
///
/// Method names use "Item" suffix to avoid conflicts with Drift's built-in methods.
abstract class ListableEntityDao<T> {
  /// Toggles the star/favorite status of an entity.
  Future<void> toggleStarItem(String id, bool isStarred);

  /// Archives an entity, hiding it from the active list.
  Future<void> archiveItem(String id);

  /// Unarchives an entity, restoring it to the active list.
  Future<void> unarchiveItem(String id);

  /// Permanently deletes an entity.
  Future<void> deleteItem(String id);

  /// Renames an entity.
  Future<void> renameItem(String id, String newName);
}
