// This file defines a common interface for Data Access Objects (DAOs)
// that manage entities intended for display in a list, such as Projects or Sessions.

// The UI component `SelectableListView` requires a way to access common
// properties (like `id`, `name`, `isStarred`) from different entity types
// (`ProjectEntity`, `SessionEntity`). Since these entities are generated by Drift
// and cannot share a common Dart interface, we use a "convention-over-configuration"
// pattern. The `SelectableListView` accepts getter functions in its constructor
// to access these properties, and it uses the `ListableEntityDao` interface
// defined here to perform common actions like starring, archiving, etc.

/// Interface for DAOs that manage listable entities.
///
/// Provides standard CRUD operations used by [SelectableListView]
/// to implement default behaviors without explicit callbacks.
///
/// Method names use "Item" suffix to avoid conflicts with Drift's built-in methods.
abstract class ListableEntityDao<T> {
  /// Toggles the star/favorite status of an entity.
  Future<void> toggleStarItem(String id, bool isStarred);

  /// Archives an entity, hiding it from the active list.
  Future<void> archiveItem(String id);

  /// Unarchives an entity, restoring it to the active list.
  Future<void> unarchiveItem(String id);

  /// Permanently deletes an entity.
  Future<void> deleteItem(String id);

  /// Renames an entity.
  Future<void> renameItem(String id, String newName);
}
